name: Client

on:
  workflow_dispatch:
  push:
    branches: main
    paths:
      - 'client/**'
  pull_request:
    paths:
      - 'client/**'

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: client
    steps:
      - name: Setup Repository
        uses: actions/checkout@v3
      - name: Install `pnpm`
        run: npm install -g pnpm
      - name: Install `model` Dependencies
        working-directory: model
        run: pnpm install
      - name: Install `client` Dependencies
        run: pnpm install
      - name: Build Project
        run: pnpm build
