name: Server Tests

on:
  workflow_dispatch:
  push:
    branches: main
    paths:
      - 'server/**'
  pull_request:
    branches: main
    paths:
      - 'server/**'

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: server
    steps:
      - name: Setup Repository
        uses: actions/checkout@v3
      - name: Install PostgreSQL Client
        run: |
          sudo apt-get update
          sudo apt-get install -y postgresql-client
      # https://github.com/actions/runner-images/blob/8361bb299ba9290b70b6ed8bf337456714c6516d/images/linux/Ubuntu2204-Readme.md#postgresql
      - name: Startup Built-in PostgreSQL Server
        run: |
          # Ubuntu 22.04 runners come with a built-in PostgreSQL service for user `postgres`.
          sudo systemctl start postgresql.service
          # Wait until the database is ready.
          pg_isready
          # Create a user for the Actions user `runner`.
          sudo -u postgres psql -c "CREATE USER runner PASSWORD 'runner'"
          # Then allocate a database for it.
          sudo -u postgres createdb -O runner doctrack
      - name: Setup PostgreSQL Database
        run: PGPASSWORD=runner psql -f db/init.sql -1 doctrack
      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
      - name: Check Type Constraints
        run: deno check src/main.ts
      - name: Run Tests
        run: deno task test
        env:
          # Many of these are just dummy values.
          PORT: 3000
          GOOGLE_ID: 'google-id'
          GOOGLE_SECRET: 'google-secret'
          OAUTH_REDIRECT: 'http://127.0.0.1:3000/auth/callback'
          HOSTED_GSUITE_DOMAIN: 'up.edu.ph'
          PG_DATABASE: 'doctrack'
          PG_USER: 'runner'
          PG_PASSWORD: 'runner'
          PG_POOL: 1
          VAPID_PRV_KEY: 'vapid-pub-key'
          VAPID_PRV_KEY: 'vapid-prv-key'
